# Introduction to Data Science 
## Assignment 02
### Mahnoor Fatima Saad - FA17-BSE-064


Mouting G-Drive to load dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Performing imports for the notebook 

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression


Importing and normalizing data from the csv file into numpy arrays for later manipulation

In [ ]:
path = '/content/drive/MyDrive/IDS/data_CHEMBL204.csv'
#getting list of columns
cols = list(pd.read_csv(path, nrows =1))
#storing arrays of labels and features separately using column headers
X = pd.read_csv(path, usecols =[i for i in cols if (i != 'molecule_id' and i != 'pXC50')])
Y = pd.read_csv(path, usecols = ['pXC50'])
print(X)
print(Y)


      b0001  b0002  b0003  b0004  b0005  ...  b1020  b1021  b1022  b1023  b1024
0         1      1      1      0      1  ...      0      1      0      0      0
1         1      1      1      1      1  ...      0      1      0      0      0
2         1      1      1      1      1  ...      0      0      0      0      0
3         1      1      1      0      1  ...      0      0      0      0      0
4         1      1      1      1      1  ...      0      0      0      0      0
...     ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
5737      1      0      1      0      1  ...      0      0      0      0      0
5738      1      0      1      0      1  ...      0      0      0      0      0
5739      1      1      1      1      1  ...      0      1      0      0      1
5740      1      0      1      1      1  ...      0      0      0      0      1
5741      1      0      1      1      1  ...      0      0      0      0      0

[5742 rows x 1024 columns]
      pXC50


Converting pd data frames to numpy arrays

In [ ]:
#converting into numpy arrays
x = np.asarray(X)
y = np.asarray(Y)
print(x)

[[1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 1]
 [1 0 1 ... 0 0 1]
 [1 0 1 ... 0 0 0]]


Splitting data into train and test sets

In [ ]:
#performing train and test split with a 0.75:0.25 ratio
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

using sklearn's linear regression model 

In [ ]:
#creating linear regression object via sklearn
linearRegressor = LinearRegression()
#fitting the linear regression model to our data
linearRegressor.fit(X_train, y_train)
print('Accuracy Score: ', linearRegressor.score(X_train, y_train))
#predicting test data on our linear regressor
y_pred = linearRegressor.predict(X_test)

Accuracy Score:  0.7699674806751446


Analyzing our model's performance using sklearn's regression metrics

In [ ]:
# sklearn metrics to analyze regression
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print(f"The R_square of prediction of (RF): {metrics.r2_score(y_test, y_pred)}")

Mean Absolute Error: 310735337.57796055
Mean Squared Error: 1.1642347329564151e+20
Root Mean Squared Error: 10789970958.980452
The R_square of prediction of (RF): -5.2119243469929914e+19


Using train test split with logistic regression

In [ ]:
# converting the continuous labels in y_test and y_train into discrete values for logistic regression
from sklearn import preprocessing
from sklearn import utils

# creating a label encoder object
lab_enc = preprocessing.LabelEncoder()

# converting y_train and y_test into a 1D array
y_train = np.ravel(y_train)
y_test = np.ravel(y_test)

# encoding y_test and y_train labels
y_train = lab_enc.fit_transform(y_train)
y_test = lab_enc.fit_transform(y_test)

#checking the type of labels we have created
print('y_train label type: ', utils.multiclass.type_of_target(y_train))
print('y_test label type: ', utils.multiclass.type_of_target(y_test))

y_train label type:  multiclass
y_test label type:  multiclass


In [ ]:
# creating the logistic regression model object 
from sklearn.linear_model import LogisticRegression
logisticRegressor = LogisticRegression(random_state=0)

# fitting the model with training data and labels
logisticRegressor.fit(X_train, y_train)

#predicting on test data
y_pred=logisticRegressor.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
# determining model accuracy score on training data 

score = logisticRegressor.score(X_train,y_train)
print('Training Accuracy Score: ',score)

# Model accuracy on test set 

print('Model Accuracy: ',metrics.accuracy_score(y_test, y_pred)*100)

Training Accuracy Score:  0.8917789131444496
Model Accuracy:  0.06963788300835655


In [ ]:
# using sklearn metrics to analyze regression
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print(f"The R_square of prediction of (RF): {metrics.r2_score(y_test, y_pred)}")

Mean Absolute Error: 270.5041782729805
Mean Squared Error: 116494.78272980501
Root Mean Squared Error: 341.313320469338
The R_square of prediction of (RF): -2.7255029484002002
